services:
  promobot:
    build: .
    container_name: promobot
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./urls_config.json:/app/urls_config.json
      - ./groups_config.json:/app/groups_config.json
      - ./coupon_config.json:/app/coupon_config.json
      - ./ml_linkbuilder_cookies.pkl:/app/ml_linkbuilder_cookies.pkl
      - ./.env:/app/.env
    environment:
      - PORT=5000
      - CHROME_BIN=/usr/bin/google-chrome
      - EVOLUTION_API_URL=http://evolution-api:8080
    depends_on:
      - evolution-api

  evolution-api:
    image: evoapicloud/evolution-api:v1.8.2
    container_name: evolution_api
    restart: unless-stopped
    ports:
      - "8070:8080"
    environment:
      - SERVER_URL=http://localhost:8070
      - DOCKER_ENV=true
      - AUTHENTICATION_API_KEY=08C1B613-4993-4C70-83D6-600E9CA0C3B8
      - DATABASE_ENABLED=false
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store

volumes:
  evolution_instances:
  evolution_store:
